package main

import (
	"context"
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"time"

	"github.com/rudi-bruchez/SqlGoPace/internal/config"
	"github.com/rudi-bruchez/SqlGoPace/internal/ddl"
	"github.com/rudi-bruchez/SqlGoPace/internal/maint"
	"github.com/rudi-bruchez/SqlGoPace/internal/mssql"
	"github.com/rudi-bruchez/SqlGoPace/internal/plan"
	"github.com/rudi-bruchez/SqlGoPace/internal/report"
	"github.com/rudi-bruchez/SqlGoPace/internal/version"
)

// namedManifest is one generated manifest with its target filename and category.
type namedManifest struct {
	filename string
	category string
	manifest *ddl.Manifest
}

// manifestCategories fixes the emission order and filename label per category. The
// category is the maint decision key; fileLabel is the (plural) filename name. The
// slice index is the category's position within a database's block.
var manifestCategories = []struct {
	category  string
	fileLabel string
	label     string // human description in the manifest header
}{
	{"checkdb", "checkdb", "integrity check"},
	{"index", "index", "index reorg/rebuild + compression"},
	{"heap", "heaps", "heap rebuilds"},
	{"statistics", "statistics", "statistics"},
}

// manifestsFromPlan groups one database's operations into per-category manifests,
// named so the engine processes them in a safe order (single-database form).
func manifestsFromPlan(pl maint.Plan, db string) []namedManifest {
	return manifestsForDatabase(pl, db, 0, 3)
}

// manifestsForDatabase emits one database's manifests as a contiguous, ordered
// block. ordinal is the database's 0-based position in a multi-database run and
// width the zero-padding of the numeric prefix, so DB0's manifests sort before
// DB1's, etc. (spec §17.5). With ordinal 0 and width 3 it reproduces the
// single-database 010/020/030/040 naming exactly.
func manifestsForDatabase(pl maint.Plan, db string, ordinal, width int) []namedManifest {
	var out []namedManifest
	for pos, mc := range manifestCategories {
		ops := pl.OperationsByCategory(mc.category)
		if len(ops) == 0 {
			continue
		}
		n := (ordinal*len(manifestCategories) + pos + 1) * 10
		out = append(out, namedManifest{
			filename: fmt.Sprintf("%0*d_maint_%s_%s.yaml", width, n, db, mc.fileLabel),
			category: mc.category,
			manifest: &ddl.Manifest{
				Description: fmt.Sprintf("Maintenance plan for %s — %s (generated by sqlgopace)", db, mc.label),
				Database:    db,
				Operations:  ops,
			},
		})
	}
	return out
}

// prefixWidth returns the zero-padding width for a multi-database run's manifest
// prefixes, wide enough for the largest prefix and never narrower than the
// single-database default (3), so small runs keep the familiar 010… naming.
func prefixWidth(numDatabases int) int {
	maxPrefix := numDatabases * len(manifestCategories) * 10
	width := len(strconv.Itoa(maxPrefix))
	if width < 3 {
		width = 3
	}
	return width
}

// runPlan is the "plan" subcommand: analyze the connected database and materialize
// reviewable maintenance manifests (or, with --dry-run, print them).
func runPlan(stdout, stderr io.Writer, args []string) error {
	fs := flag.NewFlagSet("sqlgopace plan", flag.ContinueOnError)
	fs.SetOutput(stderr)
	var (
		configPath   = fs.String("config", "", "path to config.yaml (connection + default output directory)")
		profPath     = fs.String("profile", "maintenance_profile.yaml", "path to the maintenance profile")
		database     = fs.String("database", "", "single-database mode: the database to plan (default: the connected database)")
		allDatabases = fs.Bool("all-databases", false, "multi-database mode: plan every eligible user database (spec §17)")
		databases    = fs.String("databases", "", "multi-database mode: comma-separated list of databases to plan")
		categories   = fs.String("categories", "", "comma-separated subset of: "+strings.Join(plan.AllCategories, ", ")+" (default: all)")
		outDir       = fs.String("out", "", "directory to write manifests into (default: the config's to_run)")
		dryRun       = fs.Bool("dry-run", false, "print the manifests instead of writing them")
		explain      = fs.Bool("explain", false, "show the reasoning behind each decision")
	)
	if err := fs.Parse(args); err != nil {
		if errors.Is(err, flag.ErrHelp) {
			return nil
		}
		return err
	}
	if *configPath == "" {
		return errors.New("plan requires --config (for the connection)")
	}

	cfg, err := config.Load(*configPath)
	if err != nil {
		return err
	}
	profile, err := maint.LoadFile(*profPath)
	if err != nil {
		return err
	}
	cats, err := plan.ParseCategories(*categories)
	if err != nil {
		return err
	}
	out := *outDir
	if out == "" {
		out = cfg.Directories.ToRun
	}

	ctx := context.Background()
	conn, err := mssql.Open(ctx, cfg.Database.ConnectionString, version.Version())
	if err != nil {
		return err
	}
	defer func() { _ = conn.Close() }()

	fmt.Fprintf(stdout, "-- sqlgopace %s — plan\n", version.Version())

	// Multi-database mode (spec §17): --all-databases or --databases.
	if *allDatabases || strings.TrimSpace(*databases) != "" {
		return planMulti(ctx, stdout, conn, cfg, profile, cats, out, *allDatabases, splitDatabases(*databases), *dryRun, *explain)
	}

	// Single-database mode (the default).
	db := *database
	if db == "" {
		if db, err = conn.CurrentDatabase(ctx); err != nil {
			return err
		}
	}
	pl, err := plan.Analyze(ctx, conn, profile, cats, db, stdout)
	if err != nil {
		return err
	}
	manifests := manifestsFromPlan(pl, db)

	// Pre-shrink pass (connected database only): a reorganize→shrink manifest and a
	// heap advisory, when the profile's shrink section is enabled.
	shrinkNM, heapAdvisories, err := planShrink(ctx, conn, profile, db, stdout)
	if err != nil {
		return err
	}
	if shrinkNM != nil {
		manifests = append(manifests, *shrinkNM)
	}

	if *explain {
		renderDecisions(stdout, pl)
	}
	printHeapAdvisory(stdout, heapAdvisories)
	if *dryRun {
		return renderManifests(stdout, manifests)
	}
	if err := writeManifests(stdout, out, manifests); err != nil {
		return err
	}
	if shrinkNM != nil {
		if path, err := writeHeapAdvisorySidecar(out, shrinkNM.filename, db, heapAdvisories); err != nil {
			return err
		} else if path != "" {
			fmt.Fprintf(stdout, "wrote %s\n", path)
		}
	}
	recordPlanHistory(ctx, stdout, cfg, db, pl, manifests)
	return nil
}

// planMulti runs the plan over several databases (spec §17.5): it surveys
// eligibility, resolves the scope, and for each selected database opens a
// connection in that database's context, analyses it, and emits its manifests as a
// contiguous per-database block. Ineligible/excluded databases are skipped+logged;
// a per-database connection or analysis failure skips that database, never the run.
func planMulti(ctx context.Context, stdout io.Writer, conn *mssql.Conn, cfg *config.Config, profile *maint.Profile, cats plan.Categories, out string, allFlag bool, explicit []string, dryRun, explain bool) error {
	all, err := conn.UserDatabases(ctx)
	if err != nil {
		return err
	}
	connected, err := conn.CurrentDatabase(ctx)
	if err != nil {
		return err
	}
	selected, skipped := resolveDatabases(all, allFlag, explicit, connected, profile)
	for _, s := range skipped {
		fmt.Fprintf(stdout, "-- skip database %s: %s\n", s.name, s.reason)
	}
	if len(selected) == 0 {
		fmt.Fprintln(stdout, "-- nothing to do: no databases in scope")
		return nil
	}
	fmt.Fprintf(stdout, "-- planning %d database(s): %s\n", len(selected), strings.Join(selected, ", "))

	width := prefixWidth(len(selected))
	var allManifests []namedManifest
	for i, db := range selected {
		dbConn, err := mssql.OpenDatabase(ctx, cfg.Database.ConnectionString, db, version.Version())
		if err != nil {
			fmt.Fprintf(stdout, "-- skip database %s: connect: %v\n", db, err)
			continue
		}
		pl, err := plan.Analyze(ctx, dbConn, profile, cats, db, stdout)
		_ = dbConn.Close()
		if err != nil {
			fmt.Fprintf(stdout, "-- skip database %s: analyze: %v\n", db, err)
			continue
		}
		if explain {
			fmt.Fprintf(stdout, "-- %s:\n", db)
			renderDecisions(stdout, pl)
		}
		manifests := manifestsForDatabase(pl, db, i, width)
		allManifests = append(allManifests, manifests...)
		if !dryRun {
			recordPlanHistory(ctx, stdout, cfg, db, pl, manifests)
		}
	}

	if dryRun {
		return renderManifests(stdout, allManifests)
	}
	return writeManifests(stdout, out, allManifests)
}

// autoPlan analyses the database through r and returns the generated manifests and
// the full decision plan. It is the shared core of single-database `plan` and `--auto`.
func autoPlan(ctx context.Context, r plan.Reader, profile *maint.Profile, cats plan.Categories, db string, logw io.Writer) ([]namedManifest, maint.Plan, error) {
	pl, err := plan.Analyze(ctx, r, profile, cats, db, logw)
	if err != nil {
		return nil, maint.Plan{}, err
	}
	return manifestsFromPlan(pl, db), pl, nil
}

// runAuto implements the run path's --auto flag: analyze the connected database and
// materialize the generated maintenance manifests into the queue (the config's
// to_run), so the engine then processes them like any other manifests. It records
// the analysis to history, same as the plan subcommand.
func runAuto(ctx context.Context, w io.Writer, conn *mssql.Conn, cfg *config.Config, a autoConfig) error {
	profile, err := maint.LoadFile(a.profile)
	if err != nil {
		return err
	}
	cats, err := plan.ParseCategories(a.categories)
	if err != nil {
		return err
	}

	// Multi-database --auto: materialize per-database manifest blocks into the
	// queue; runEngine's per-database loop then executes them.
	if a.allDatabases || strings.TrimSpace(a.databases) != "" {
		return planMulti(ctx, w, conn, cfg, profile, cats, cfg.Directories.ToRun, a.allDatabases, splitDatabases(a.databases), false, false)
	}

	db := a.database
	if db == "" {
		if db, err = conn.CurrentDatabase(ctx); err != nil {
			return err
		}
	}

	fmt.Fprintf(w, "-- auto: analyzing %s\n", db)
	manifests, pl, err := autoPlan(ctx, conn, profile, cats, db, w)
	if err != nil {
		return err
	}
	if len(manifests) == 0 {
		fmt.Fprintln(w, "-- auto: nothing to do")
		return nil
	}
	if err := writeManifests(w, cfg.Directories.ToRun, manifests); err != nil {
		return err
	}
	recordPlanHistory(ctx, w, cfg, db, pl, manifests)
	return nil
}

// recordPlanHistory persists the plan's emitted decisions to the local SQLite
// history, when enabled. It is best-effort: a failure is logged, never fatal.
func recordPlanHistory(ctx context.Context, w io.Writer, cfg *config.Config, db string, pl maint.Plan, manifests []namedManifest) {
	if !cfg.History.Enabled {
		return
	}
	h, err := report.OpenHistory(sqlitePath(cfg.History.Destination))
	if err != nil {
		fmt.Fprintf(w, "-- history: %v\n", err)
		return
	}
	defer func() { _ = h.Close() }()

	var recs []report.MaintenanceDecisionRecord
	for _, d := range pl.Decisions {
		if d.Op == nil { // record only emitted operations (the actionable set)
			continue
		}
		recs = append(recs, report.MaintenanceDecisionRecord{
			Category: d.Category, Target: d.Target, Decision: d.Kind, Reason: d.Reason,
			PageCount: d.Metrics.PageCount, SizeMB: d.Metrics.SizeMB,
			FragmentationPercent: d.Metrics.FragmentationPercent, ForwardedPercent: d.Metrics.ForwardedPercent,
			WriteRatio: d.Metrics.WriteRatio, CurrentCompression: d.Metrics.CurrentCompression,
			ChosenCompression: d.Metrics.ChosenCompression,
		})
	}
	run := report.MaintenancePlanRecord{
		Database: db, GeneratedAt: time.Now().UTC().Format(time.RFC3339),
		Manifests: len(manifests), Operations: len(recs),
	}
	if err := h.RecordMaintenance(ctx, run, recs); err != nil {
		fmt.Fprintf(w, "-- history: %v\n", err)
		return
	}
	fmt.Fprintf(w, "-- recorded %d decision(s) to history (%s)\n", len(recs), cfg.History.Destination)
}

// renderDecisions prints the reasoning trail grouped by category.
func renderDecisions(w io.Writer, pl maint.Plan) {
	fmt.Fprintln(w, "-- analysis:")
	for _, d := range pl.Decisions {
		fmt.Fprintf(w, "--   [%s] %s → %s (%s)\n", d.Category, d.Target, d.Kind, d.Reason)
	}
}

// renderManifests prints each manifest's YAML to w (dry-run).
func renderManifests(w io.Writer, manifests []namedManifest) error {
	if len(manifests) == 0 {
		fmt.Fprintln(w, "-- nothing to do: no operations selected")
		return nil
	}
	for _, nm := range manifests {
		data, err := ddl.MarshalManifest(nm.manifest)
		if err != nil {
			return err
		}
		fmt.Fprintf(w, "\n-- %s (%d operations)\n%s", nm.filename, len(nm.manifest.Operations), data)
	}
	return nil
}

// writeManifests writes each manifest into dir, creating it if needed.
func writeManifests(w io.Writer, dir string, manifests []namedManifest) error {
	if len(manifests) == 0 {
		fmt.Fprintln(w, "-- nothing to do: no operations selected")
		return nil
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("create output directory: %w", err)
	}
	written := make([]string, 0, len(manifests))
	for _, nm := range manifests {
		data, err := ddl.MarshalManifest(nm.manifest)
		if err != nil {
			return err
		}
		path := filepath.Join(dir, nm.filename)
		if err := os.WriteFile(path, data, 0o644); err != nil {
			return fmt.Errorf("write %s: %w", path, err)
		}
		written = append(written, nm.filename)
	}
	sort.Strings(written)
	for _, name := range written {
		fmt.Fprintf(w, "wrote %s\n", filepath.Join(dir, name))
	}
	fmt.Fprintf(w, "%d manifest(s) written to %s — review, then run: sqlgopace --config <config>\n", len(written), dir)
	return nil
}
