package main

import (
	"fmt"
	"io"
	"os"
	"path/filepath"

	"gopkg.in/yaml.v3"

	"github.com/rudi-bruchez/SqlGoPace/internal/ddl"
	"github.com/rudi-bruchez/SqlGoPace/internal/maint"
)

// shrinkManifest assembles the dedicated shrink manifest for the connected database:
// the density-selected reorganizes (in pre, empty when pre_reorganize is off or the
// shrink is a log shrink) followed by the shrink operation. Returns nil when the shrink
// section is disabled. Filename sorts after the maintenance manifests (010–040).
func shrinkManifest(profile *maint.Profile, db string, pre maint.PreShrinkPlan) *namedManifest {
	s := profile.Shrink
	if !s.Enabled {
		return nil
	}
	ops := make([]ddl.Operation, 0, len(pre.Reorganizes)+1)
	for _, ro := range pre.Reorganizes {
		ops = append(ops, ro)
	}
	shrink := ddl.Shrink{Type: s.Type, Files: s.Files, TargetFreeSpace: s.TargetFreeSpace}
	if s.MaxBlockMinutes > 0 {
		mb := s.MaxBlockMinutes
		shrink.Options.MaxBlockMinutes = &mb
	}
	ops = append(ops, shrink)

	typ := "data"
	if s.IsLog() {
		typ = "log"
	}
	return &namedManifest{
		filename: fmt.Sprintf("050_shrink_%s_%s.yaml", db, typ),
		category: "shrink",
		manifest: &ddl.Manifest{
			Description: fmt.Sprintf("Pre-shrink reorganize + reclaim for %s — %s (generated by sqlgopace)", db, typ),
			Database:    db,
			Operations:  ops,
		},
	}
}

// heapAdvisoryDoc is the .heaps.yaml advisory sidecar. Advisory only — SqlGoPace never
// reads it back (mirrors the .blocked.yaml convention).
type heapAdvisoryDoc struct {
	Advisory string             `yaml:"advisory"`
	Database string             `yaml:"database"`
	Heaps    []heapAdvisoryItem `yaml:"heaps"`
}

type heapAdvisoryItem struct {
	Schema                 string  `yaml:"schema"`
	Table                  string  `yaml:"table"`
	SizeMB                 int64   `yaml:"size_mb"`
	ForwardedRecordPercent float64 `yaml:"forwarded_record_percent"`
	PageDensityPercent     float64 `yaml:"page_density_percent"`
}

const heapAdvisoryText = "Heaps cannot be reorganized in-row (reorganize only compacts their LOB pages). " +
	"These low-density heaps may keep the shrink from reaching target; rebuild them with a rebuild_heap " +
	"manifest in a maintenance window (offline/blocking on Standard edition), or give them a clustered index. " +
	"Candidates by property (size/density), not confirmed tail position."

// printHeapAdvisory prints the advisory summary to w (both dry-run and real runs).
func printHeapAdvisory(w io.Writer, advisories []maint.HeapAdvisory) {
	if len(advisories) == 0 {
		return
	}
	fmt.Fprintf(w, "-- heap advisory: %d heap(s) reorganize cannot help before the shrink:\n", len(advisories))
	for _, a := range advisories {
		fmt.Fprintf(w, "--   %s.%s  %d MB  density %.0f%%  forwarded %.0f%%\n",
			a.Schema, a.Table, a.SizeMB, a.PageDensityPercent, a.ForwardedRecordPercent)
	}
}

// writeHeapAdvisorySidecar writes the .heaps.yaml sidecar next to the shrink manifest
// and returns its path. It returns ("", nil) when there are no advisories.
func writeHeapAdvisorySidecar(dir, shrinkFilename, db string, advisories []maint.HeapAdvisory) (string, error) {
	if len(advisories) == 0 {
		return "", nil
	}
	doc := heapAdvisoryDoc{Advisory: heapAdvisoryText, Database: db}
	for _, a := range advisories {
		doc.Heaps = append(doc.Heaps, heapAdvisoryItem{
			Schema: a.Schema, Table: a.Table, SizeMB: a.SizeMB,
			ForwardedRecordPercent: a.ForwardedRecordPercent, PageDensityPercent: a.PageDensityPercent,
		})
	}
	data, err := yaml.Marshal(doc)
	if err != nil {
		return "", fmt.Errorf("marshal heap advisory: %w", err)
	}
	path := filepath.Join(dir, shrinkFilename+".heaps.yaml")
	if err := os.WriteFile(path, data, 0o644); err != nil {
		return "", fmt.Errorf("write heap advisory: %w", err)
	}
	return path, nil
}
