package main

import (
	"context"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/rudi-bruchez/SqlGoPace/internal/ddl"
	"github.com/rudi-bruchez/SqlGoPace/internal/maint"
	"github.com/rudi-bruchez/SqlGoPace/internal/plan"
)

// confirmedSetFor validates a contended doc against the connected database and returns
// the object_id -> Confirmation map. Empty database in the doc, or a mismatch, is an
// error — a sidecar captured against a different database would silently misattribute.
func confirmedSetFor(doc maint.ContendedDoc, db string) (map[int64]maint.Confirmation, error) {
	if !strings.EqualFold(doc.Database, db) {
		return nil, fmt.Errorf("--confirmed sidecar is for database %q, connected to %q", doc.Database, db)
	}
	set := make(map[int64]maint.Confirmation, len(doc.Observed))
	for _, o := range doc.Observed {
		set[o.ObjectID] = maint.Confirmation{
			TimesBlocked: o.TimesBlocked,
			ByTail:       o.ConfirmedBy == "tail_position",
			IndexID:      o.IndexID,
			PageFromEnd:  o.PageFromEnd,
		}
	}
	return set, nil
}

// shrinkManifest assembles the dedicated shrink manifest for the connected database:
// the density-selected reorganizes (in pre, empty when pre_reorganize is off or the
// shrink is a log shrink) followed by the shrink operation. Returns nil when the shrink
// section is disabled. Filename sorts after the maintenance manifests (010–040).
func shrinkManifest(profile *maint.Profile, db string, pre maint.PreShrinkPlan) *namedManifest {
	s := profile.Shrink
	if !s.Enabled {
		return nil
	}
	ops := make([]ddl.Operation, 0, len(pre.Reorganizes)+1)
	for _, ro := range pre.Reorganizes {
		ops = append(ops, ro)
	}
	shrink := ddl.Shrink{Type: s.Type, Files: s.Files, TargetFreeSpace: s.TargetFreeSpace}
	if s.MaxBlockMinutes > 0 {
		mb := s.MaxBlockMinutes
		shrink.Options.MaxBlockMinutes = &mb
	}
	ops = append(ops, shrink)

	typ := "data"
	if s.IsLog() {
		typ = "log"
	}
	comments := map[int]string{}
	for i, note := range pre.ReorganizeNotes {
		if note != "" {
			comments[i] = note
		}
	}
	return &namedManifest{
		filename: fmt.Sprintf("050_shrink_%s_%s.yaml", db, typ),
		category: "shrink",
		manifest: &ddl.Manifest{
			Description: fmt.Sprintf("Pre-shrink reorganize + reclaim for %s — %s (generated by sqlgopace)", db, typ),
			Database:    db,
			Operations:  ops,
		},
		comments: comments,
	}
}

// planShrink gathers the pre-shrink density (only for an enabled data shrink with
// pre_reorganize on), assembles the shrink manifest, and returns it with the heap
// advisories. confirmed is the object_id -> Confirmation set from a --confirmed
// sidecar (nil when none was given); it prioritizes and annotates matching reorganizes
// and marks matching heap advisories CONFIRMED. Returns (nil, nil, nil) when the shrink
// section is disabled.
func planShrink(ctx context.Context, r plan.Reader, profile *maint.Profile, db string, confirmed map[int64]maint.Confirmation, logw io.Writer) (*namedManifest, []maint.HeapAdvisory, error) {
	if !profile.Shrink.Enabled {
		return nil, nil, nil
	}
	var pre maint.PreShrinkPlan
	if !profile.Shrink.IsLog() && profile.Shrink.PreReorganizeEnabled() {
		var err error
		if pre, err = plan.AnalyzePreShrink(ctx, r, profile, confirmed, logw); err != nil {
			return nil, nil, err
		}
	} else if len(confirmed) > 0 {
		fmt.Fprintln(logw, "-- warning: --confirmed has no effect for a log shrink or pre_reorganize:false; ignored")
	}
	return shrinkManifest(profile, db, pre), pre.HeapAdvisories, nil
}

// heapAdvisoryDoc is the .heaps.yaml advisory sidecar. Advisory only — SqlGoPace never
// reads it back (mirrors the .blocked.yaml convention).
type heapAdvisoryDoc struct {
	Advisory string             `yaml:"advisory"`
	Database string             `yaml:"database"`
	Heaps    []heapAdvisoryItem `yaml:"heaps"`
}

type heapAdvisoryItem struct {
	Schema                 string  `yaml:"schema"`
	Table                  string  `yaml:"table"`
	SizeMB                 int64   `yaml:"size_mb"`
	ForwardedRecordPercent float64 `yaml:"forwarded_record_percent"`
	PageDensityPercent     float64 `yaml:"page_density_percent"`
	Confirmed              bool    `yaml:"confirmed,omitempty"`
	TimesBlocked           int     `yaml:"times_blocked,omitempty"`
}

const heapAdvisoryText = "Heaps cannot be reorganized in-row (reorganize only compacts their LOB pages). " +
	"These low-density heaps may keep the shrink from reaching target; rebuild them with a rebuild_heap " +
	"manifest in a maintenance window (offline/blocking on Standard edition), or give them a clustered index. " +
	"Candidates by property (size/density), not confirmed tail position."

// printHeapAdvisory prints the advisory summary to w (both dry-run and real runs).
func printHeapAdvisory(w io.Writer, advisories []maint.HeapAdvisory) {
	if len(advisories) == 0 {
		return
	}
	fmt.Fprintf(w, "-- heap advisory: %d heap(s) reorganize cannot help before the shrink:\n", len(advisories))
	for _, a := range advisories {
		line := fmt.Sprintf("--   %s.%s  %d MB  density %.0f%%  forwarded %.0f%%",
			a.Schema, a.Table, a.SizeMB, a.PageDensityPercent, a.ForwardedRecordPercent)
		if a.Confirmed {
			line += fmt.Sprintf(" [CONFIRMED, times_blocked=%d]", a.TimesBlocked)
		}
		fmt.Fprintln(w, line)
	}
}

// writeHeapAdvisorySidecar writes the .heaps.yaml sidecar next to the shrink manifest
// and returns its path. It returns ("", nil) when there are no advisories.
func writeHeapAdvisorySidecar(dir, shrinkFilename, db string, advisories []maint.HeapAdvisory) (string, error) {
	if len(advisories) == 0 {
		return "", nil
	}
	doc := heapAdvisoryDoc{Advisory: heapAdvisoryText, Database: db}
	for _, a := range advisories {
		doc.Heaps = append(doc.Heaps, heapAdvisoryItem{
			Schema: a.Schema, Table: a.Table, SizeMB: a.SizeMB,
			ForwardedRecordPercent: a.ForwardedRecordPercent, PageDensityPercent: a.PageDensityPercent,
			Confirmed: a.Confirmed, TimesBlocked: a.TimesBlocked,
		})
	}
	data, err := yaml.Marshal(doc)
	if err != nil {
		return "", fmt.Errorf("marshal heap advisory: %w", err)
	}
	path := filepath.Join(dir, shrinkFilename+".heaps.yaml")
	if err := os.WriteFile(path, data, 0o644); err != nil {
		return "", fmt.Errorf("write heap advisory: %w", err)
	}
	return path, nil
}
